### ISSUE TITLE
RRDB是否损坏？

### ISSUE THREAD

**Issue by triste-creator** [littlebeen/ASDDPM-Adaptive-Semantic-Enhanced-DDPM#8]
在读取权重文件rrdb.load_state_dict(torch.load('./models/LREncoder/pretrain/RRDB/model_best3.pt'), strict=False)，会RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
权重文件是否正确？

**Comment by littlebeen** [comment]
It seems like you don't put the file into the right place or the python could not find the right path. You need to put the model_best3.pt into ./models/LREncoder/pretrain/RRDB/. It is a relative path which also related to the path you run the python file. You could change it to a absolute path such as xxxx/ASDDPM-Adaptive-Semantic-Enhanced-DDPM/models/LREncoder/pretrain/RRDB/model_best3.pt.

**Comment by triste-creator** [comment]
If I want to pre-train the LREncoder model for my own data set, how do I train it? Hope you can answer, thank you very much!

**Comment by littlebeen** [comment]
Please refer to my project https://github.com/littlebeen/Remote-Sensing-Super-resolution-Model-Collection. It contains the code of RRDB in Remote-Sensing-Super-resolution-Model-Collection/src/model/rrdb.
